language: ruby
rvm:
  - 3.0
sudo: false
script: bundle exec jekyll build && bundle exec rake deploy
addons:
  apt:
    packages:
      - graphviz
env:
  global:
    - secure: YYoWlvwSzxTI4e+yUjkCzdFj1AjFN0HZZPHdsmvoujMVk4fhW0N70dYv85xaTMhWIANwbUDttu6yVsod3At1v7zG3Ky5MtpdjeV0FMRLWd6YrpJd5ZAZ5Cd+1r5BkXOM+ikUmt3t9B3s2VIimxRRnMOy8bnx4KqFAHU0qvItqX23FnZMlMGtvrd33jY5h2kwI6PhrkNw0NbZ5wIF7qHLg5X2YsO+qlvBs/tN/xaSMhrYjqejnQjvLlYu11npNY0dEggygwRbLyz3fOl9QNgqKB3M4EuTBIwIuH5ILXkRTDvoPUcUOPWBdu6gZLl7QDAR0lklUro1cCF1vqrehh8VRe7iK7QvOhSZMlynBBAFfSl7GFgkpFEjfh7XDVfLAwWisXeNqsN9ipkPim8tE2P2s4b1HVvvnHrDyLt4oLqSD/7xdCsGIkFgowoSqevlRd/UoG+pLTdHyNB6f81fFs319MbuoYuaYhI3T0hl6Kd2fLR1DiqeG7eQeJLt/Y2YNyfqdKECER4e/PAOnTIjq6lvKL4SElnhTqt5Fd9iHNTYSVbynTDuMu0hsdyAi38vfZyhToLEqrk0WDNdMeTJcH7EtHrU7euHfj4mLUEBgwk+Tn2OLcZrlfEixX8ZpkW2Inn8ZARe3S+NCTvApqxZHws/xu3BgSCqpoU7PhHFlDHjcrE=
