### Site Config
title:               Life
tagline:             'Life of a Techie'
description:         'Notes, lessons-learned, wisdom, travel-logs, hobbies, sports and all other life experiences of a Husband, Father, and a Techie.'
# comment the remote url for local developments
url:                  https://life.wijesundara.org
#url:                 http://localhost:4000

google_analytics_id: G-W54HLV2XHH

# About/contact
author:
  name:              Isuru Wijesundara
  url:               https://twitter.com/nalinda6963
  email:             isuru.wijesundara@wijesundara.org

# Social IDs
wp_username:        isuruwijesundara
github_username:    nalinda6963
twitter_username:   nalinda6963
linkedin_username:  isuruwijesundara
youtube_channel:    UC6dtuXsC78CZDqFWgYhBx8Q
###

asciidoc: {}

asciidoctor:
  attributes:
    - stem
  base_dir: :docdir
  imagesdir: /images
  safe: unsafe

collections:
  notes:
    output: true
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      author: "Isuru W."
      layout: "notes"
  - scope:
      path: ""
      type: "docs"
    values:
      author: "Isuru W."
      layout: "docs"
  - scope:
      path: ""
      type: "posts"
    values:
      author: "Isuru W."
      layout: "posts"
  - scope:
      path: ""
    values:
      author: "Isuru W."
      layout: "default"

exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .jekyll-cache

# not working with collections tags
#feed:
#  collections:
#    - notes
#    - docs
#  tags: true

keep_files:
  - images

paginate: 5

permalink: pretty

plugins:
  - jekyll-seo-tag
#  - jemoji
#  - jekyll-feed

tags:

version: 0.1.1

