# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

workflows:
  lifeSite-build-deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: develop

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  ruby: circleci/ruby@2.0.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.0
    executor: ruby/default
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - rubygems-v1-{{ checksum "Gemfile.lock" }}
      #       - rubygems-v1-fallback
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      # - save_cache:
      #     key: rubygems-v1-{{ checksum "Gemfile.lock" }}
      #     paths:
      #       - vendor/bundle
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - run:
          name: HTMLProofer tests
          command: |
            bundle exec htmlproofer ./_site \
              --allow-hash-href \
              --check-favicon  \
              --check-html \
              --disable-external
      - persist_to_workspace:
          root: ./
          paths:
            - _site
      - run:
          name: Push to GitHub
          command: bundle exec rake deploy
      - ruby/install-deps
