:imagesdir: images
:page-excerpt: This is an attempt to test the use of asciidocs
:page-created-date: 2021-03-04
:page-doctype: article
:page-title: The Value of Jetbrains Products
:page-tags: [test tag with spaces, test_tag_no_spaces, JetBrains, IntelliJ, PyCharm, WebStorm, DataGrip]
:sectanchors:
:sectlinks:
:toc:

= First Entry

== Example entry

Cura is a free slicing software. Besides the fact this is free, Cura is one of the best slicing software options in the industry. It is necessary to have the right profile, matching your printer, loaded to get the best printing experience. The latest version of cura can be downloaded from https://ultimaker.com/software/ultimaker-cura[here].

== Test level 2 title
Cura is a free slicing software. Besides the fact this is free, Cura is one of the best slicing software options in the industry. It is necessary to have the right profile, matching your printer, loaded to get the best printing experience. The latest version of cura can be downloaded from https://ultimaker.com/software/ultimaker-cura[here].

=== Test level 3 title
Cura is a free slicing software. Besides the fact this is free, Cura is one of the best slicing software options in the industry. It is necessary to have the right profile, matching your printer, loaded to get the best printing experience. The latest version of cura can be downloaded from https://ultimaker.com/software/ultimaker-cura[here].

[plantuml, plantuml-example-2, svg]
----
class Dummy {
 -field1
 #field2
 ~method1()
 +method2()
}
----

[plantuml, test-1, svg]
----
start
:Hello world;
:This is defined on
several **lines**;
stop
----

[plantuml, test-2, svg]
----
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
----

[plantuml, test-3, svg]
----
Alice -> Bob: Authentication Request
Bob -> Alice: Authentication Failure
group My own label [My own label 2]
    Alice -> Log : Log attack start
    loop 1000 times
        Alice -> Bob: DNS Attack
    end
    Alice -> Log : Log attack end
end
----

[plantuml, simple-auth-flow, svg]
----
User -> Web_UI: access login
Web_UI -> IDP: authentication request
IDP -> IDP: validate the client
IDP -> User: login page
User -> IDP: username / password
IDP -> IDP: authenticate user
IDP -> Web_UI: redirect with the JWT token
Web_UI -> API_Gateway: api call with JWT
API_Gateway -> API_Gateway: validate token and claims
API_Gateway -> IDP: validate token signature
API_Gateway -> BackEnd: api call with JWT
BackEnd -> BackEnd: validate claims
BackEnd -> Web_UI: response
----

[ditaa, ascii-diagram, svg]
----
+--------+   +-------+    +-------+
|        +---+ ditaa +--> |       |
|  Text  |   +-------+    |diagram|
|Document|   |!magic!|    |       |
|     {d}|   |       |    |       |
+---+----+   +-------+    +-------+
    :                         ^
    |       Lots of work      |
    +-------------------------+
----

[graphviz, node-diagram, png]
----
digraph foo {
  node [style=rounded]
  node1 [shape=box]
  node2 [fillcolor=yellow, style="rounded,filled", shape=diamond]
  node3 [shape=record, label="{ a | b | c }"]

  node1 -> node2 -> node3
}
----

[graphviz, cyclic, png]
----
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
----

[ditaa, memory, svg]
----

      +--------+
   0  |        |  <- start
      +--------+
   1  |        |  <- q  scans from start to end
      +--------+
      :  ..... |
      +--------+
      |        |  <- end
      +--------+  <-+
      |        |    |
      +--------+    | rest of the
      :  ..... |    | allocated memory
      +--------+    |
  n   |        |    |
      +--------+  <-+
----
